insert into department(name) values('Administrative Reforms & PG');
insert into department (name) values ('Dairying and Fisheries');
insert into department (name) values ('Bio-Technology');
insert into department (name) values ('Chemicals & Petrochemicals');
insert into department (name) values ('Commerce');
insert into department (name) values ('Consumer Affairs');
insert into department (name) values ('Defence');
insert into department (name) values ('Defence Production');
insert into department (name) values ('Defence Research & Development');
insert into department (name) values ('Disinvestment');
insert into department (name) values ('Economic Affairs');
insert into department (name) values ('Expenditure');
insert into department (name) values ('Ex-Servicemen Welfare');
insert into department (name) values ('Fertilisers');
insert into department (name) values ('Financial Services');
insert into department (name) values ('Food & Public Distribution');
insert into department (name) values ('Health & Family Welfare');
insert into department (name) values ('Health Research');
insert into department (name) values ('Heavy Industries');
insert into department (name) values ('Higher Education');
insert into department (name) values ('Industrial Policy & Promotion');
insert into department (name) values ('Home');
insert into department (name) values ('Information Technology');
insert into department (name) values ('Justice');
insert into department (name) values ('Land Resources');
insert into department (name) values ('Legal Affairs');
insert into department (name) values ('Pensions & Pensioners Welfare');
insert into department (name) values ('Personnel & Training');
insert into department (name) values ('Pharmaceuticals');
insert into department (name) values ('Posts');
insert into department (name) values ('Public Enterprises');
insert into department (name) values ('Revenue');
insert into department (name) values ('Development');
insert into department (name) values ('School Education and Literacy');
insert into department (name) values ('Science & Technology');
insert into department (name) values ('Scientific & Industrial Research');
insert into department (name) values ('Telecommunications');
insert into department (name) values ('Legislative Department');
insert into department (name) values ('Production');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Purchasing');
insert into department (name) values ('Marketing');
insert into department (name) values ('Human Resource Management');
insert into department (name) values ('Accounting and Finance');
insert into department (name) values ('Marketing and Advertising');
insert into department (name) values ('Production and Inventory');
insert into department (name) values ('Sales & Marketing');
insert into department (name) values ('Sanitary');
insert into department (name) values ('Security');
insert into department (name) values ('Stores');
insert into department (name) values ('Sports');
insert into department (name) values ('Physics');
insert into department (name) values ('Chemistry');
insert into department (name) values ('Math');
insert into department (name) values ('Political Science');
insert into department (name) values ('English');
insert into department (name) values ('Hindi');
insert into department (name) values ('Marathi');
insert into department (name) values ('German');
insert into department (name) values ('Plantation');
insert into department (name) values ('Infrastructure');
insert into department (name) values ('Testing');
insert into department (name) values ('Software Development');
insert into department (name) values ('Electronic Data Processing');
insert into department (name) values ('Networking');
insert into department (name) values ('Cabling');
insert into department (name) values ('Water supply');
insert into department (name) values ('Stationery');
insert into department (name) values ('Maintenance');
insert into department (name) values ('Literature');
insert into department (name) values ('Washing');
insert into department (name) values ('Cooking');
insert into department (name) values ('Parking');
insert into department (name) values ('Printing');
insert into department (name) values ('Roofing');
insert into department (name) values ('Library');
insert into department (name) values ('Reservation');
